add

diff --git a/.github/workflows/candle-image-task.yml b/.github/workflows/candle-image-task.yml
--- a/.github/workflows/candle-image-task.yml
+++ b/.github/workflows/candle-image-task.yml
@@ -54,6 +54,13 @@ jobs:
                 cd candle;
                 /root/.cargo/bin/cargo build --example whisper --release || echo 'cargo build failed.';
                 ls;
+                WHISPER_BINARY_PATH=/root/candle/target/release/examples/whisper
+                if [ -f "$WHISPER_BINARY_PATH" ]; then
+                    echo "Whisper binary successfully built at: $WHISPER_BINARY_PATH"
+                else
+                    echo "Failed to find whisper binary after build."
+                    exit 1
+                fi
                 " \
             --query "value[].message" --output tsv)
         echo "Command Output:"
diff --git a/.github/workflows/download-upload-whisper.yml b/.github/workflows/download-upload-whisper.yml
--- a/.github/workflows/download-upload-whisper.yml
+++ b/.github/workflows/download-upload-whisper.yml
@@ -41,31 +41,40 @@ jobs:
       #   shell: bash
 
 
-      - name: Find Whisper Binary in VM
-        run: |
-          WHISPER_PATHS=$(ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP "find / -type f -name whisper 2>/dev/null" || echo "find_error")
-          if [[ "$WHISPER_PATHS" == "find_error" ]]; then
-            echo "Error executing find command on the VM."
-            exit 1
-          fi
-          if [[ -z "$WHISPER_PATHS" ]]; then
-            echo "The whisper binary was not found on the VM."
-            exit 1
-          fi
-          # Handling potential multiple paths
-          IFS=$'\n' read -rd '' -a WHISPER_ARRAY <<< "$WHISPER_PATHS"
-          if (( ${#WHISPER_ARRAY[@]} > 1 )); then
-            echo "Multiple whisper binaries found:"
-            printf '%s\n' "${WHISPER_ARRAY[@]}"
-            # Choose the correct binary path, here assuming the first one
-            WHISPER_PATH=${WHISPER_ARRAY[0]}
-          else
-            WHISPER_PATH=$WHISPER_PATHS
-          fi
-          CANDLE_DIR=$(dirname "$WHISPER_PATH")
-          echo "CANDLE_DIR is set to $CANDLE_DIR"
-        shell: bash
+      # - name: Find Whisper Binary in VM
+      #   run: |
+      #     WHISPER_PATHS=$(ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP "find / -type f -name whisper 2>/dev/null" || echo "find_error")
+      #     if [[ "$WHISPER_PATHS" == "find_error" ]]; then
+      #       echo "Error executing find command on the VM."
+      #       exit 1
+      #     fi
+      #     if [[ -z "$WHISPER_PATHS" ]]; then
+      #       echo "The whisper binary was not found on the VM."
+      #       exit 1
+      #     fi
+      #     # Handling potential multiple paths
+      #     IFS=$'\n' read -rd '' -a WHISPER_ARRAY <<< "$WHISPER_PATHS"
+      #     if (( ${#WHISPER_ARRAY[@]} > 1 )); then
+      #       echo "Multiple whisper binaries found:"
+      #       printf '%s\n' "${WHISPER_ARRAY[@]}"
+      #       # Choose the correct binary path, here assuming the first one
+      #       WHISPER_PATH=${WHISPER_ARRAY[0]}
+      #     else
+      #       WHISPER_PATH=$WHISPER_PATHS
+      #     fi
+      #     CANDLE_DIR=$(dirname "$WHISPER_PATH")
+      #     echo "CANDLE_DIR is set to $CANDLE_DIR"
+      #   shell: bash
     
+      - name: Verify Whisper Binary in VM
+        run: |
+          if ssh -o StrictHostKeyChecking=no $VM_USER@$VM_IP "test -f /root/candle/target/release/examples/whisper"; then
+            echo "Whisper binary exists at /root/candle/target/release/examples/whisper."
+          else
+            echo "The whisper binary was not found at the expected location."
+            exit 1
+          fi
+        shell: bash
 
 
       - name: Check Whisper Binary Exists in Known Directory
