add file

diff --git a/.github/workflows/candle-image-task.yml b/.github/workflows/candle-image-task.yml
--- a/.github/workflows/candle-image-task.yml
+++ b/.github/workflows/candle-image-task.yml
@@ -71,6 +71,7 @@ jobs:
                 WHISPER_BINARY_PATH=\"\$(pwd)/whisper\"
                 if [ -f \"\$WHISPER_BINARY_PATH\" ]; then
                     chmod +x "$WHISPER_BINARY_PATH"
+                    "$WHISPER_BINARY_PATH" || { echo 'Failed to run whisper'; exit 1; }
                     echo \"Whisper binary exists at \$WHISPER_BINARY_PATH\"
 
                     # Set HOME environment variable explicitly for Git
@@ -103,10 +104,10 @@ jobs:
                     fi
 
                     # Track the binary using Git LFS
-                    git lfs track "target/release/examples/whisper"
+                    git lfs track "$(basename "$WHISPER_BINARY_PATH")"
 
                     # Add the binary to Git
-                    git add -f target/release/examples/whisper
+                    git add -f $(basename "$WHISPER_BINARY_PATH")
 
                     git commit -m "Add whisper binary"
                     if git push origin main; then
