change back to invoke

diff --git a/.github/workflows/candle-image-task.yml b/.github/workflows/candle-image-task.yml
--- a/.github/workflows/candle-image-task.yml
+++ b/.github/workflows/candle-image-task.yml
@@ -10,131 +10,68 @@ on:
         required: true
 
 jobs:
-  build-and-release:
-    runs-on: self-hosted # Make sure this matches the labels of your self-hosted runner
+  run-candle-image-task:
+    runs-on: ubuntu-latest
     steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v2
 
-      - name: Install Dependencies
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y build-essential pkg-config libssl-dev
-
-      - name: Install Rust
-        run: |
-          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
-          echo "source $HOME/.cargo/env" >> $GITHUB_ENV
-
-      - name: Clone and Build Candle
-        run: |
-          git clone https://github.com/huggingface/candle.git
-          cd candle
-          cargo build --example whisper --release
-
-      - name: Check Whisper Binary
-        run: |
-          if [ ! -f "candle/target/release/examples/whisper" ]; then
-            echo "Whisper binary not found."
-            exit 1
-          fi
-
-      - name: Install GitHub CLI
-        run: |
-          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
-          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
-          sudo apt update
-          sudo apt install gh
-
-      - name: Authenticate GitHub CLI
-        run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
-
-      - name: Create GitHub Release
-        env:
-          WHISPER_BINARY: ./candle/target/release/examples/whisper
-        run: |
-          gh release create V.0.1 "$WHISPER_BINARY" --title 'New Whisper Release V.0.1' --notes 'Whisper binary release for GNU/Linux.'
-
-
-
-
-
-
-
-# name: Candle Image Task
-
-# on:
-#   repository_dispatch:
-#     types: [candle-image-task]
-#   workflow_dispatch:
-#     inputs:
-#       vm_name:
-#         description: 'Name of the VM to run tasks on'
-#         required: true
-
-# jobs:
-#   run-candle-image-task:
-#     runs-on: ubuntu-latest
-#     steps:
-
-#     - name: Azure Login
-#       uses: azure/login@v1
-#       with:
-#         creds: ${{ secrets.AZURE_CREDENTIALS }}
+    - name: Azure Login
+      uses: azure/login@v1
+      with:
+        creds: ${{ secrets.AZURE_CREDENTIALS }}
         
-#     - name: Run Candle Image Task
-#       run: |
-#         VM_NAME="${{ github.event.client_payload.vm_name || github.event.inputs.vm_name }}"
-#         OUTPUT=$(az vm run-command invoke\
-#             --resource-group githubVM \
-#             --name "$VM_NAME" \
-#             --command-id RunShellScript \
-#             --scripts "
-#                 #!/bin/bash
-#                 set -e
-#                 # Install C compiler and related tools
-#                 apt-get update
-#                 apt-get install -y build-essential pkg-config libssl-dev
-#                 # Now install Rust
-#                 curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y;
-#                 echo 'Checking installation...'
-#                 CARGO_HOME='/root/.cargo'
-#                 RUSTUP_HOME='/root/.rustup'
-#                 echo \"CARGO_HOME: \$CARGO_HOME\";
-#                 echo \"RUSTUP_HOME: \$RUSTUP_HOME\";
-#                 if [ -d \"\$CARGO_HOME/bin\" ]; then
-#                     echo '.cargo/bin directory exists.'
-#                     ls -alh \"\$CARGO_HOME/bin\"
-#                 else
-#                     echo '.cargo/bin directory NOT found.'
-#                     exit 1
-#                 fi
-#                 # Using the bash shell to source the environment variables
-#                 /bin/bash -c \"source \$CARGO_HOME/env\"
-#                 echo \$PATH
-#                 /root/.cargo/bin/rustc --version || echo 'rustc not found after installation.'
-#                 git clone https://github.com/huggingface/candle.git;
-#                 cd candle;
-#                 /root/.cargo/bin/cargo build --example whisper --release || echo 'cargo build failed.';
-#                 # Navigate to the build directory
-#                 cd target/release/examples
-#                 ./whisper
-#                 # Install GitHub CLI
-#                 curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
-#                 echo \"deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main\" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
-#                 apt update
-#                 apt install gh
+    - name: Run Candle Image Task
+      run: |
+        VM_NAME="${{ github.event.client_payload.vm_name || github.event.inputs.vm_name }}"
+        OUTPUT=$(az vm run-command invoke\
+            --resource-group githubVM \
+            --name "$VM_NAME" \
+            --command-id RunShellScript \
+            --scripts "
+                #!/bin/bash
+                set -e
+                # Install C compiler and related tools
+                apt-get update
+                apt-get install -y build-essential pkg-config libssl-dev
+                # Now install Rust
+                curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y;
+                echo 'Checking installation...'
+                CARGO_HOME='/root/.cargo'
+                RUSTUP_HOME='/root/.rustup'
+                echo \"CARGO_HOME: \$CARGO_HOME\";
+                echo \"RUSTUP_HOME: \$RUSTUP_HOME\";
+                if [ -d \"\$CARGO_HOME/bin\" ]; then
+                    echo '.cargo/bin directory exists.'
+                    ls -alh \"\$CARGO_HOME/bin\"
+                else
+                    echo '.cargo/bin directory NOT found.'
+                    exit 1
+                fi
+                # Using the bash shell to source the environment variables
+                /bin/bash -c \"source \$CARGO_HOME/env\"
+                echo \$PATH
+                /root/.cargo/bin/rustc --version || echo 'rustc not found after installation.'
+                git clone https://github.com/huggingface/candle.git;
+                cd candle;
+                /root/.cargo/bin/cargo build --example whisper --release || echo 'cargo build failed.';
+                # Navigate to the build directory
+                cd target/release/examples
+                ./whisper
+                # Install GitHub CLI
+                curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
+                echo \"deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main\" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
+                apt update
+                apt install gh
 
-#                 # Authenticate with GitHub CLI using a token from secrets
-#                 echo ${{ secrets.PAT }} | gh auth login --with-token
+                # Authenticate with GitHub CLI using a token from secrets
+                echo ${{ secrets.PAT }} | gh auth login --with-token
 
-#                 # Create a new GitHub release with the version tag V.0.1
-#                 gh release create V.0.1 \"$WHISPER_BINARY\" --title 'New Whisper Release V.0.1' --notes 'Whisper binary release for GNU/Linux.'
+                # Create a new GitHub release with the version tag V.0.1
+                gh release create V.0.1 \"$WHISPER_BINARY\" --title 'New Whisper Release V.0.1' --notes 'Whisper binary release for GNU/Linux.'
 
-#                 " \
-#             --query "value[].message" --output tsv)
-#         echo "Command Output:"
-#         echo "$OUTPUT"
+                " \
+            --query "value[].message" --output tsv)
+        echo "Command Output:"
+        echo "$OUTPUT"
     
 
 
