add

diff --git a/.github/workflows/candle-image-task.yml b/.github/workflows/candle-image-task.yml
--- a/.github/workflows/candle-image-task.yml
+++ b/.github/workflows/candle-image-task.yml
@@ -54,12 +54,12 @@ jobs:
                 /root/.cargo/bin/rustc --version || echo 'rustc not found after installation.'
                 git clone https://github.com/huggingface/candle.git;
                 cd candle;
-                # /root/.cargo/bin/cargo build --example whisper --release || echo 'cargo build failed.';
-                cargo build --example whisper --release
+                /root/.cargo/bin/cargo build --example whisper --release || echo 'cargo build failed.';
                 # Navigate to the build directory
                 # cd target/release/examples
                 # ./whisper
                 # After build, upload the binary to Azure Blob Storage
+                WHISPER_BINARY_PATH='./target/release/examples/'
                 if [ -f "$WHISPER_BINARY_PATH" ]; then
                     echo "Whisper binary exists at $WHISPER_BINARY_PATH"
                     # Upload the binary to Azure Blob Storage
