add

diff --git a/.github/workflows/candle-image-task.yml b/.github/workflows/candle-image-task.yml
--- a/.github/workflows/candle-image-task.yml
+++ b/.github/workflows/candle-image-task.yml
@@ -58,14 +58,15 @@ jobs:
                 cd candle;
                 /root/.cargo/bin/cargo build --example whisper --release || echo 'cargo build failed.';
 
-                # Locate the whisper binary dynamically
-                # Locate the whisper binary dynamically
-                WHISPER_BINARY_PATH=$(sudo find /var/lib/waagent/run-command/download -type f -name whisper | head -n 1)
-                if [ -z "$WHISPER_BINARY_PATH" ]; then
-                    echo 'Whisper binary not found.'
+                # Define the whisper binary path based on the current working directory
+                WHISPER_BINARY_PATH=\"\$(pwd)/target/release/examples/whisper\"
+                if [ -f \"\$WHISPER_BINARY_PATH\" ]; then
+                    chmod +x \"\$WHISPER_BINARY_PATH\"
+                    \"\$WHISPER_BINARY_PATH\" || echo 'Whisper run failed.'
+                else
+                    echo \"Whisper binary not found at \$WHISPER_BINARY_PATH\"
                     exit 1
                 fi
-
 
                 # Make sure the binary is executable
                 chmod +x \"$WHISPER_BINARY_PATH\"
@@ -148,61 +149,3 @@ jobs:
             --query "value[].message" --output tsv)
         echo "Command Output:"
         echo "$OUTPUT"
-
-
-
-
-    # - name: Download Whisper Binary
-    #   run: |
-    #     mkdir -p ~/.ssh
-    #     echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
-    #     chmod 600 ~/.ssh/id_rsa
-    #     scp -o StrictHostKeyChecking=no runner@172.191.177.239:/root/candle/target/release/examples/whisper .
-    #   env:
-    #     VM_USER: runner
-    #     SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_PRIVATE_KEY }}
-
-    # - name: Track with Git LFS
-    #   run: |
-    #     git lfs track "whisper"
-    #     git add .gitattributes whisper
-
-    # - name: Commit and push Whisper binary
-    #   run: |
-    #     git config --local user.email "action@github.com"
-    #     git config --local user.name "GitHub Action"
-    #     git commit -m "Add Whisper binary with LFS" -- whisper .gitattributes
-    #     git push
-
-    # - name: Download Whisper Binary
-    #   env:
-    #     VM_NAME: ${{ github.event.client_payload.vm_name || github.event.inputs.vm_name }}
-    #     VM_USER: runner # Replace with your VM's user name
-    #     VM_IP: 172.191.39.190 # Replace with your VM's public IP address
-    #     SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_PRIVATE_KEY }}
-
-    #     run: |
-    #       mkdir -p ~/.ssh
-    #       echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
-    #       chmod 600 ~/.ssh/id_rsa
-    #       # Use SCP to copy the binary from VM to the GitHub runner
-    #       scp -o StrictHostKeyChecking=no $VM_USER@172.191.177.239:/candle/target/release/examples/whisper .
-    #     shell: bash
-    #     env:
-    #       VM_USER: runner
-    #       SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_PRIVATE_KEY }}
-      
-
-    # - name: Upload Whisper Binary
-    #   uses: actions/upload-artifact@v2
-    #   with:
-    #     name: whisper-binary
-    #     path: ./whisper # If you copied the file to the current directory
-  
-
-
-    # cargo new myapp; cd myapp; ls; cargo build --example whisper --release; ls; cd target/release/examples; ls
-    # - name: Deallocate VM
-    #   run: |
-    #     VM_NAME="${{ github.event.client_payload.vm_name || github.event.inputs.vm_name }}"
-    #     az vm deallocate --resource-group githubVM --name "$VM_NAME"
