add

diff --git a/.github/workflows/candle-image-task.yml b/.github/workflows/candle-image-task.yml
--- a/.github/workflows/candle-image-task.yml
+++ b/.github/workflows/candle-image-task.yml
@@ -43,20 +43,20 @@ jobs:
                 echo \"CARGO_HOME: \$CARGO_HOME\";
                 echo \"RUSTUP_HOME: \$RUSTUP_HOME\";
 
-                # if [ -d \"\$CARGO_HOME/bin\" ]; then
-                #     echo '.cargo/bin directory exists.'
-                #     ls -alh \"\$CARGO_HOME/bin\"
-                # else
-                #     echo '.cargo/bin directory NOT found.'
-                #     exit 1
-                # fi
-                # # Using the bash shell to source the environment variables
-                # /bin/bash -c \"source \$CARGO_HOME/env\"
-                # echo \$PATH
-                # /root/.cargo/bin/rustc --version || echo 'rustc not found after installation.'
-                # git clone https://github.com/huggingface/candle.git;
-                # cd candle;
-                # /root/.cargo/bin/cargo build --example whisper --release || echo 'cargo build failed.';
+                if [ -d \"\$CARGO_HOME/bin\" ]; then
+                    echo '.cargo/bin directory exists.'
+                    ls -alh \"\$CARGO_HOME/bin\"
+                else
+                    echo '.cargo/bin directory NOT found.'
+                    exit 1
+                fi
+                # Using the bash shell to source the environment variables
+                /bin/bash -c \"source \$CARGO_HOME/env\"
+                echo \$PATH
+                /root/.cargo/bin/rustc --version || echo 'rustc not found after installation.'
+                git clone https://github.com/huggingface/candle.git;
+                cd candle;
+                /root/.cargo/bin/cargo build --example whisper --release || echo 'cargo build failed.';
 
 
                 # Navigate to the build directory
