add

diff --git a/.github/workflows/candle-image-task.yml b/.github/workflows/candle-image-task.yml
--- a/.github/workflows/candle-image-task.yml
+++ b/.github/workflows/candle-image-task.yml
@@ -54,23 +54,25 @@ jobs:
                 /root/.cargo/bin/rustc --version || echo 'rustc not found after installation.'
                 git clone https://github.com/huggingface/candle.git;
                 cd candle;
-                /root/.cargo/bin/cargo build --example whisper --release || echo 'cargo build failed.';
+                # /root/.cargo/bin/cargo build --example whisper --release || echo 'cargo build failed.';
+                cargo build --example whisper --release
                 # Navigate to the build directory
                 # cd target/release/examples
                 # ./whisper
                 # After build, upload the binary to Azure Blob Storage
-                WHISPER_BINARY_PATH=\$(find \$(pwd) -type f -name whisper)
-                if [[ -f "\$WHISPER_BINARY_PATH" ]]; then
-                    echo "Whisper binary exists at \$WHISPER_BINARY_PATH"
+                if [ -f "$WHISPER_BINARY_PATH" ]; then
+                    echo "Whisper binary exists at $WHISPER_BINARY_PATH"
+                    # Upload the binary to Azure Blob Storage
                     az storage blob upload \
                       --account-name candle \
-                      --account-key \$STORAGE_ACCOUNT_KEY \
+                      --account-key $STORAGE_ACCOUNT_KEY \
                       --container-name whisper-binaries \
-                      --file "\$WHISPER_BINARY_PATH" \
+                      --file "$WHISPER_BINARY_PATH" \
                       --name whisper
                 else
-                    echo "Whisper binary not found at \$WHISPER_BINARY_PATH"
-                    find / -type f -name whisper  # This will search the entire filesystem for the binary, which is useful for debugging
+                    echo "Whisper binary not found"
+                    # List the contents of the target/release/examples directory for debugging
+                    ls -la ./target/release/examples
                     exit 1
                 fi
                 " \
