add

diff --git a/.github/workflows/candle-image-task.yml b/.github/workflows/candle-image-task.yml
--- a/.github/workflows/candle-image-task.yml
+++ b/.github/workflows/candle-image-task.yml
@@ -13,6 +13,7 @@ jobs:
   run-candle-image-task:
     runs-on: ubuntu-latest
     steps:
+
     - name: Azure Login
       uses: azure/login@v1
       with:
@@ -21,7 +22,7 @@ jobs:
     - name: Run Candle Image Task
       run: |
         VM_NAME="${{ github.event.client_payload.vm_name || github.event.inputs.vm_name }}"
-        OUTPUT=$(az vm run-command invoke \
+        OUTPUT=$(az vm run-command invoke\
             --resource-group githubVM \
             --name "$VM_NAME" \
             --command-id RunShellScript \
@@ -31,17 +32,27 @@ jobs:
                 # Install C compiler and related tools
                 apt-get update
                 apt-get install -y build-essential pkg-config libssl-dev
-                # Install Rust
-                curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
+                # Now install Rust
+                curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y;
                 echo 'Checking installation...'
                 CARGO_HOME='/root/.cargo'
                 RUSTUP_HOME='/root/.rustup'
+                echo \"CARGO_HOME: \$CARGO_HOME\";
+                echo \"RUSTUP_HOME: \$RUSTUP_HOME\";
+                if [ -d \"\$CARGO_HOME/bin\" ]; then
+                    echo '.cargo/bin directory exists.'
+                    ls -alh \"\$CARGO_HOME/bin\"
+                else
+                    echo '.cargo/bin directory NOT found.'
+                    exit 1
+                fi
                 # Using the bash shell to source the environment variables
-                source \$CARGO_HOME/env
-                rustc --version || (echo 'rustc not found after installation.' && exit 1)
-                git clone https://github.com/huggingface/candle.git
-                cd candle
-                cargo build --example whisper --release || (echo 'cargo build failed.' && exit 1)
+                /bin/bash -c \"source \$CARGO_HOME/env\"
+                echo \$PATH
+                /root/.cargo/bin/rustc --version || echo 'rustc not found after installation.'
+                git clone https://github.com/huggingface/candle.git;
+                cd candle;
+                /root/.cargo/bin/cargo build --example whisper --release || echo 'cargo build failed.';
                 # Navigate to the build directory
                 cd target/release/examples
                 # Check if the Whisper binary exists
@@ -63,7 +74,6 @@ jobs:
             --query "value[].message" --output tsv)
         echo "Command Output:"
         echo "$OUTPUT"
-
     
     # - name: Download Whisper Binary
     #   run: |
