add file

diff --git a/.github/workflows/candle-image-task.yml b/.github/workflows/candle-image-task.yml
--- a/.github/workflows/candle-image-task.yml
+++ b/.github/workflows/candle-image-task.yml
@@ -68,10 +68,10 @@ jobs:
                 ls -al
 
                 # Check if whisper binary exists in the expected location
-                WHISPER_BINARY_PATH=\"\$(pwd)/whisper\"
+                WHISPER_BINARY_PATH="$(pwd)/whisper"
                 if [ -f \"\$WHISPER_BINARY_PATH\" ]; then
                     chmod +x "$WHISPER_BINARY_PATH"
-                    "$WHISPER_BINARY_PATH" || { echo 'Failed to run whisper'; exit 1; }
+                    # "$WHISPER_BINARY_PATH" || { echo 'Failed to run whisper'; exit 1; }
                     echo \"Whisper binary exists at \$WHISPER_BINARY_PATH\"
 
                     # Set HOME environment variable explicitly for Git
