add

diff --git a/.github/workflows/candle-image-task.yml b/.github/workflows/candle-image-task.yml
--- a/.github/workflows/candle-image-task.yml
+++ b/.github/workflows/candle-image-task.yml
@@ -13,7 +13,6 @@ jobs:
   run-candle-image-task:
     runs-on: ubuntu-latest
     steps:
-
     - name: Azure Login
       uses: azure/login@v1
       with:
@@ -22,7 +21,7 @@ jobs:
     - name: Run Candle Image Task
       run: |
         VM_NAME="${{ github.event.client_payload.vm_name || github.event.inputs.vm_name }}"
-        OUTPUT=$(az vm run-command invoke\
+        OUTPUT=$(az vm run-command invoke \
             --resource-group githubVM \
             --name "$VM_NAME" \
             --command-id RunShellScript \
@@ -32,37 +31,28 @@ jobs:
                 # Install C compiler and related tools
                 apt-get update
                 apt-get install -y build-essential pkg-config libssl-dev
-                # Now install Rust
-                curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y;
+                # Install Rust
+                curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
                 echo 'Checking installation...'
                 CARGO_HOME='/root/.cargo'
                 RUSTUP_HOME='/root/.rustup'
-                echo \"CARGO_HOME: \$CARGO_HOME\";
-                echo \"RUSTUP_HOME: \$RUSTUP_HOME\";
-                if [ -d \"\$CARGO_HOME/bin\" ]; then
-                    echo '.cargo/bin directory exists.'
-                    ls -alh \"\$CARGO_HOME/bin\"
-                else
-                    echo '.cargo/bin directory NOT found.'
-                    exit 1
-                fi
                 # Using the bash shell to source the environment variables
-                /bin/bash -c \"source \$CARGO_HOME/env\"
-                echo \$PATH
-                /root/.cargo/bin/rustc --version || echo 'rustc not found after installation.'
-                git clone https://github.com/huggingface/candle.git;
-                cd candle;
-                /root/.cargo/bin/cargo build --example whisper --release || echo 'cargo build failed.';
-
-                WHISPER_BINARY=./target/release/examples/Whisper
-                if [ -f \"$WHISPER_BINARY\" ]; then
+                source \$CARGO_HOME/env
+                rustc --version || (echo 'rustc not found after installation.' && exit 1)
+                git clone https://github.com/huggingface/candle.git
+                cd candle
+                cargo build --example whisper --release || (echo 'cargo build failed.' && exit 1)
+                # Navigate to the build directory
+                cd target/release/examples
+                # Check if the Whisper binary exists
+                WHISPER_BINARY='./whisper'
+                if [ -f "\$WHISPER_BINARY" ]; then
                     # Configure Git and LFS
                     git config --global user.email \"scott.lai@duke.edu\"
                     git config --global user.name \"scottLL\"
                     git lfs install
-                    git lfs track \"$WHISPER_BINARY\"
-                    # Commit and push the binary
-                    git add \"$WHISPER_BINARY\"
+                    git lfs track \"*.whisper\" # Replace with actual file extension
+                    git add .gitattributes "\$WHISPER_BINARY"
                     git commit -m \"Add whisper binary\"
                     git push origin main
                 else
@@ -73,6 +63,7 @@ jobs:
             --query "value[].message" --output tsv)
         echo "Command Output:"
         echo "$OUTPUT"
+
     
     # - name: Download Whisper Binary
     #   run: |
