add

diff --git a/.github/workflows/candle-image-task.yml b/.github/workflows/candle-image-task.yml
--- a/.github/workflows/candle-image-task.yml
+++ b/.github/workflows/candle-image-task.yml
@@ -57,21 +57,21 @@ jobs:
                 cd candle;
                 /root/.cargo/bin/cargo build --example whisper --release || echo 'cargo build failed.';
                 # Navigate to the build directory
-                # cd target/release/examples
+                cd target/release/examples
 
                 # Navigate to the build directory
-                cd /var/lib/waagent/run-command/download/15/candle/target/release/examples
+                # cd /var/lib/waagent/run-command/download/15/candle/target/release/examples
 
                 # Before running the binary, ensure it has execute permissions
                 chmod +x whisper
 
-                # Now attempt to run the whisper binary
-                if ./whisper; then
-                    echo "Whisper binary executed successfully."
-                else
-                    echo "Failed to execute Whisper binary."
-                    exit 1
-                fi
+                # # Now attempt to run the whisper binary
+                # if ./whisper; then
+                #     echo "Whisper binary executed successfully."
+                # else
+                #     echo "Failed to execute Whisper binary."
+                #     exit 1
+                # fi
 
                 # Confirm current directory
                 echo \"Current directory:\"
