add file

diff --git a/.github/workflows/candle-image-task.yml b/.github/workflows/candle-image-task.yml
--- a/.github/workflows/candle-image-task.yml
+++ b/.github/workflows/candle-image-task.yml
@@ -39,28 +39,21 @@ jobs:
                 df -h
 
                 # Install Rust
-                curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
+                curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y;
+                echo 'Checking installation...'
                 CARGO_HOME='/root/.cargo'
                 RUSTUP_HOME='/root/.rustup'
-                echo \"CARGO_HOME: \$CARGO_HOME\"
-                echo \"RUSTUP_HOME: \$RUSTUP_HOME\"
+                echo \"CARGO_HOME: \$CARGO_HOME\";
+                echo \"RUSTUP_HOME: \$RUSTUP_HOME\";
 
-                if [ -d \"\$CARGO_HOME/bin\" ]; then
-                    echo '.cargo/bin directory exists.'
-                    ls -alh \"\$CARGO_HOME/bin\"
-                else
-                    echo '.cargo/bin directory NOT found.'
-                    exit 1
-                fi
-
+                # Using the bash shell to source the environment variables
                 /bin/bash -c \"source \$CARGO_HOME/env\"
-                rustc --version || { echo 'Rust installation failed'; exit 1; }
-                cargo --version || { echo 'Cargo installation failed'; exit 1; }
+                echo \$PATH
+                /root/.cargo/bin/rustc --version || echo 'rustc not found after installation.'
+                git clone https://github.com/huggingface/candle.git;
+                cd candle;
+                /root/.cargo/bin/cargo build --example whisper --release || echo 'cargo build failed.';
 
-                # Clone and build the project
-                git clone https://github.com/huggingface/candle.git
-                cd candle
-                cargo build --example whisper --release || { echo 'cargo build failed'; exit 1; }
 
                 # Navigate to the build directory
                 cd target/release/examples
