add

diff --git a/.github/workflows/candle-image-task.yml b/.github/workflows/candle-image-task.yml
--- a/.github/workflows/candle-image-task.yml
+++ b/.github/workflows/candle-image-task.yml
@@ -61,27 +61,17 @@ jobs:
                 /root/.cargo/bin/rustc --version || echo 'rustc not found after installation.'
                 git clone https://github.com/huggingface/candle.git;
                 cd candle;
-                /root/.cargo/bin/cargo build --example whisper --release || echo 'cargo build failed.';
-                # ls -l target/release/examples
-                # pwd
-                # # Store the path of the project directory
-                # PROJECT_DIR=$(pwd)
-                # echo 'Project directory:' "$PROJECT_DIR"
-        
-
-                # Dynamically find the project directory and store it
-                PROJECT_DIR=$(find / -type d -name "candle" 2>/dev/null | grep 'waagent/run-command/download')
+                # Get the current directory which is the project directory
+                PROJECT_DIR=$(pwd)
                 echo "Project directory: $PROJECT_DIR"
+                /root/.cargo/bin/cargo build --example whisper --release || echo 'cargo build failed.';
 
-                # Navigate to the binary directory
+                # Define the binary directory based on the project directory
                 BINARY_DIR="$PROJECT_DIR/target/release/examples"
                 echo "Binary directory: $BINARY_DIR"
+
+                # Navigate to the binary directory
                 cd "$BINARY_DIR" || { echo "Failed to change directory to $BINARY_DIR"; exit 1; }
-
-
-                # Navigate to the build directory
-                cd target/release/examples || *** echo "Failed to change directory"; exit 1; ***
-                echo 'Current directory:' "$(pwd)"
         
                 if [ -f whisper ]; then
                     echo 'Whisper binary compiled successfully'
@@ -93,26 +83,15 @@ jobs:
                 # Navigate back to the project root
                 cd "$PROJECT_DIR"
         
+                # Perform Git operations
+                cd "$PROJECT_DIR"
                 git init
                 git config --global user.email "scott.lai@duke.edu"
                 git config --global user.name "scottLL"
-                git remote set-url origin https://github.com/nogibjj/candle_scott_Azure_vm.git
-        
-                # Track and commit LFS files
+                git remote add origin https://github.com/nogibjj/candle_scott_Azure_vm.git
                 echo 'target/release/examples/whisper filter=lfs diff=lfs merge=lfs -text' > .gitattributes
                 git lfs track "target/release/examples/whisper"
-        
-                # # Debugging: Check current directory and git status
-                # echo 'Current directory before git add:'
-                # pwd
-                # git status
-        
-                # Navigate to the directory where the whisper binary is located
-                # cd /home/runner/work/candle_scott_Azure_vm/candle_scott_Azure_vm/candle/target/release/examples
-                ls -l home/runner/work/candle_scott_Azure_vm/candle_scott_Azure_vm
-
-                # Now add the whisper binary to Git
-                git add whisper
+                git add whisper .gitattributes
                 git commit -m 'Add whisper binary'
                 git push -u origin main
                 " \
